name = "Rat's Mischief ğŸ€"
filename = "ratsmischief-1.3.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3738/376/ratsmischief-1.3.6.jar"
hash-format = "sha1"
hash = "f2398b2f52061b91c422ac2ec9741dab52493afe"

[update]
[update.curseforge]
file-id = 3738376
project-id = 431787
